spring.application.name=servicebooking

spring.datasource.url=jdbc:h2:file:./data/servicebookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.config.import=optional:file:.env.properties
gemini.api.key=${GEMINI_API_KEY}
debug=true